### ISSUE TITLE
quitting and re-joining a mesh with stable identity results in peer count increase

### ISSUE THREAD

**Issue by jkbecker** [serval/kaboodle#13]
As far as I understood, the identity payloads PR #12 serves the purpose of being able to re-identify a node that goes offline and re-joins later.

When I run the 2x2 demo, and stop & start one of the nodes (top-left) repeatedly, all other nodes experience an increment in known peers. Seems like a bug? 

https://user-images.githubusercontent.com/31668498/223435778-a0ceabac-e79b-4b20-8f89-406951aeefb8.mp4

**Comment by shinypb** [comment]
There was a bug in the indirect ping mechanism that was causing down peers to hang around forever. The fix was dumb: https://github.com/serval/kaboodle/commit/114fba3
